spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "${GOOGLE_CLIENT_ID}" # Environment variable or external config
            clientSecret: "${GOOGLE_CLIENT_SECRET}" # Use environment variable or external config
          github:
            clientId: "${GITHUB_CLIENT_ID}" # Use environment variable or external config
            clientSecret: "${GITHUB_CLIENT_SECRET}" # Use environment variable or external config
